apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: encryption-key
            {{- if .Values.n8n.basicAuth.enabled }}
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: basic-auth-user
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: basic-auth-password
            {{- end }}
            {{- if eq .Values.n8n.database.type "postgresdb" }}
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: {{ .Values.n8n.database.postgresdb.host }}
            - name: DB_POSTGRESDB_PORT
              value: {{ .Values.n8n.database.postgresdb.port | quote }}
            - name: DB_POSTGRESDB_DATABASE
              value: {{ .Values.n8n.database.postgresdb.database }}
            - name: DB_POSTGRESDB_USER
              value: {{ .Values.n8n.database.postgresdb.user }}
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: database-password
            {{- end }}
            {{- if eq .Values.n8n.database.type "mysqldb" }}
            - name: DB_TYPE
              value: mysqldb
            - name: DB_MYSQLDB_HOST
              value: {{ .Values.n8n.database.mysqldb.host }}
            - name: DB_MYSQLDB_PORT
              value: {{ .Values.n8n.database.mysqldb.port | quote }}
            - name: DB_MYSQLDB_DATABASE
              value: {{ .Values.n8n.database.mysqldb.database }}
            - name: DB_MYSQLDB_USER
              value: {{ .Values.n8n.database.mysqldb.user }}
            - name: DB_MYSQLDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: database-password
            {{- end }}
            {{- if .Values.n8n.smtp.enabled }}
            - name: N8N_EMAIL_MODE
              value: smtp
            - name: N8N_SMTP_HOST
              value: {{ .Values.n8n.smtp.host }}
            - name: N8N_SMTP_PORT
              value: {{ .Values.n8n.smtp.port | quote }}
            - name: N8N_SMTP_USER
              value: {{ .Values.n8n.smtp.user }}
            - name: N8N_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: smtp-password
            - name: N8N_SMTP_SENDER
              value: {{ .Values.n8n.smtp.sender }}
            - name: N8N_SMTP_SSL
              value: {{ .Values.n8n.smtp.ssl | quote }}
            {{- end }}
            # Environment variables for n8n 1.82.3
            - name: N8N_WEBHOOK_TIMEOUT
              value: {{ .Values.n8n.webhook.timeout | quote }}
            - name: N8N_EXECUTION_TIMEOUT
              value: {{ .Values.n8n.execution.timeout | quote }}
            - name: N8N_EXECUTION_MAX_TIMEOUT
              value: {{ .Values.n8n.execution.maxTimeout | quote }}
            - name: N8N_GENERIC_TIMEZONE
              value: {{ .Values.n8n.generic.timezone }}
            - name: N8N_GENERIC_DATE_FORMAT
              value: {{ .Values.n8n.generic.dateFormat | quote }}
            - name: N8N_GENERIC_TIME_FORMAT
              value: {{ .Values.n8n.generic.timeFormat | quote }}
            - name: N8N_SECURITY_EXCLUDE_ENDPOINTS
              value: {{ .Values.n8n.security.excludeEndpoints | quote }}
            - name: N8N_NODES_EXCLUDE
              value: {{ .Values.n8n.nodes.exclude | quote }}
            - name: N8N_NODES_INCLUDE
              value: {{ .Values.n8n.nodes.include | quote }}
            - name: N8N_TELEMETRY_ENABLED
              value: {{ .Values.n8n.telemetry.enabled | quote }}
            - name: N8N_LOGS_LEVEL
              value: {{ .Values.n8n.logs.level }}
            - name: N8N_LOGS_OUTPUT
              value: {{ .Values.n8n.logs.output }}
            - name: N8N_EDITOR_BASE_URL
              value: {{ .Values.n8n.editor.baseUrl | quote }}
            - name: N8N_WORKFLOW_TAGS_DISABLED
              value: {{ .Values.n8n.workflow.tags.disabled | quote }}
            - name: N8N_WORKFLOW_CALL_POLICY_ENABLED
              value: {{ .Values.n8n.workflow.callPolicy.enabled | quote }}
            - name: N8N_WORKFLOW_CALL_POLICY_ALLOWED_DOMAINS
              value: {{ .Values.n8n.workflow.callPolicy.allowedDomains | quote }}
            - name: N8N_WORKFLOW_SHARING_ENABLED
              value: {{ .Values.n8n.workflow.sharing.enabled | quote }}
            - name: N8N_WORKFLOW_HISTORY_PRUNED
              value: {{ .Values.n8n.workflow.history.pruned | quote }}
            - name: N8N_WORKFLOW_HISTORY_MAX_AGE
              value: {{ .Values.n8n.workflow.history.maxAge | quote }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_SAVE_EXECUTION_DATA
              value: {{ .Values.n8n.workflow.defaultSettings.saveExecutionData | quote }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_SAVE_MANUAL_EXECUTIONS
              value: {{ .Values.n8n.workflow.defaultSettings.saveManualExecutions | quote }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_SAVE_DATA_ERROR_EXECUTION
              value: {{ .Values.n8n.workflow.defaultSettings.saveDataErrorExecution | quote }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_SAVE_DATA_SUCCESS_EXECUTION
              value: {{ .Values.n8n.workflow.defaultSettings.saveDataSuccessExecution | quote }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_EXECUTION_TIMEOUT
              value: {{ .Values.n8n.workflow.defaultSettings.executionTimeout | quote }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_TIMEZONE
              value: {{ .Values.n8n.workflow.defaultSettings.timezone }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_SAVE_DATA_ERROR_EXECUTION_ALL
              value: {{ .Values.n8n.workflow.defaultSettings.saveDataErrorExecutionAll | quote }}
            - name: N8N_WORKFLOW_DEFAULT_SETTINGS_SAVE_DATA_SUCCESS_EXECUTION_ALL
              value: {{ .Values.n8n.workflow.defaultSettings.saveDataSuccessExecutionAll | quote }}
            # New environment variables for n8n 1.82.3
            - name: N8N_BINARY_DATA_MAX_SIZE
              value: {{ .Values.n8n.binaryData.maxSize | quote }}
            - name: N8N_BINARY_DATA_TTL
              value: {{ .Values.n8n.binaryData.ttl | quote }}
            {{- if .Values.n8n.queue.bull.redis.host }}
            - name: N8N_QUEUE_BULL_REDIS_HOST
              value: {{ .Values.n8n.queue.bull.redis.host }}
            - name: N8N_QUEUE_BULL_REDIS_PORT
              value: {{ .Values.n8n.queue.bull.redis.port | quote }}
            - name: N8N_QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: redis-password
            - name: N8N_QUEUE_BULL_REDIS_DB
              value: {{ .Values.n8n.queue.bull.redis.db | quote }}
            - name: N8N_QUEUE_BULL_PREFIX
              value: {{ .Values.n8n.queue.bull.prefix | quote }}
            {{- end }}
            - name: N8N_RATE_LIMIT_MAX
              value: {{ .Values.n8n.rateLimit.max | quote }}
            - name: N8N_RATE_LIMIT_WINDOW_MS
              value: {{ .Values.n8n.rateLimit.windowMs | quote }}
            {{- if .Values.n8n.security.jwt.secret }}
            - name: N8N_SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: jwt-secret
            - name: N8N_SECURITY_JWT_EXPIRES_IN
              value: {{ .Values.n8n.security.jwt.expiresIn | quote }}
            {{- end }}
            {{- if .Values.n8n.security.ldap.enabled }}
            - name: N8N_SECURITY_LDAP_ENABLED
              value: "true"
            - name: N8N_SECURITY_LDAP_URL
              value: {{ .Values.n8n.security.ldap.url }}
            - name: N8N_SECURITY_LDAP_BIND_DN
              value: {{ .Values.n8n.security.ldap.bindDn }}
            - name: N8N_SECURITY_LDAP_BIND_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.fullname" . }}
                  key: ldap-bind-credentials
            - name: N8N_SECURITY_LDAP_SEARCH_BASE
              value: {{ .Values.n8n.security.ldap.searchBase }}
            - name: N8N_SECURITY_LDAP_SEARCH_FILTER
              value: {{ .Values.n8n.security.ldap.searchFilter }}
            - name: N8N_SECURITY_LDAP_GROUP_SEARCH_BASE
              value: {{ .Values.n8n.security.ldap.groupSearchBase }}
            - name: N8N_SECURITY_LDAP_GROUP_SEARCH_FILTER
              value: {{ .Values.n8n.security.ldap.groupSearchFilter }}
            {{- end }}
            {{- if .Values.n8n.security.saml.enabled }}
            - name: N8N_SECURITY_SAML_ENABLED
              value: "true"
            - name: N8N_SECURITY_SAML_ENTRY_POINT
              value: {{ .Values.n8n.security.saml.entryPoint }}
            - name: N8N_SECURITY_SAML_ISSUER
              value: {{ .Values.n8n.security.saml.issuer }}
            - name: N8N_SECURITY_SAML_CERT
              value: {{ .Values.n8n.security.saml.cert }}
            - name: N8N_SECURITY_SAML_KEY
              value: {{ .Values.n8n.security.saml.key }}
            - name: N8N_SECURITY_SAML_CALLBACK_URL
              value: {{ .Values.n8n.security.saml.callbackUrl }}
            - name: N8N_SECURITY_SAML_WANT_ASSERTIONS_SIGNED
              value: {{ .Values.n8n.security.saml.wantAssertionsSigned | quote }}
            - name: N8N_SECURITY_SAML_WANT_RESPONSE_SIGNED
              value: {{ .Values.n8n.security.saml.wantResponseSigned | quote }}
            - name: N8N_SECURITY_SAML_WANT_AUTHN_RESPONSE_SIGNED
              value: {{ .Values.n8n.security.saml.wantAuthnResponseSigned | quote }}
            - name: N8N_SECURITY_SAML_SIGNATURE_VALIDATION_TYPE
              value: {{ .Values.n8n.security.saml.signatureValidationType }}
            - name: N8N_SECURITY_SAML_ALLOWED_CLOCK_DRIFT
              value: {{ .Values.n8n.security.saml.allowedClockDrift | quote }}
            - name: N8N_SECURITY_SAML_IDENTIFIER_FORMAT
              value: {{ .Values.n8n.security.saml.identifierFormat }}
            - name: N8N_SECURITY_SAML_AUTHN_REQUEST_BINDING
              value: {{ .Values.n8n.security.saml.authnRequestBinding }}
            - name: N8N_SECURITY_SAML_LOGOUT_REQUEST_BINDING
              value: {{ .Values.n8n.security.saml.logoutRequestBinding }}
            - name: N8N_SECURITY_SAML_LOGOUT_RESPONSE_BINDING
              value: {{ .Values.n8n.security.saml.logoutResponseBinding }}
            - name: N8N_SECURITY_SAML_SKIP_REQUEST_COMPRESSION
              value: {{ .Values.n8n.security.saml.skipRequestCompression | quote }}
            - name: N8N_SECURITY_SAML_ACCEPTED_CLOCK_SKEW_MS
              value: {{ .Values.n8n.security.saml.acceptedClockSkewMs | quote }}
            - name: N8N_SECURITY_SAML_DISABLE_REQUESTED_AUTHN_CONTEXT
              value: {{ .Values.n8n.security.saml.disableRequestedAuthnContext | quote }}
            - name: N8N_SECURITY_SAML_SCOPING_ALLOW_IDP_INITIATED
              value: {{ .Values.n8n.security.saml.scoping.allowIdpInitiated | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
