{{- if .Values.ingress.enabled -}}
{{- $fullName := include "n8n.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: intranet-sig-lan-ca-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  className: nginx
  enabled: true
  hosts:
    - host: n8n.intranet.sig.lan
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - n8n.intranet.sig.lan
      secretName: n8n-secret-tls
{{- end }}