{{- if .Values.ingress.enabled -}}
ingress:
  annotations:
    cert-manager.io/cluster-issuer: intranet-sig-lan-ca-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  className: nginx
  enabled: true
  hosts:
    - host: {{ .Values.ingress.domainName }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingress.domainName }}
      secretName: {{ .Release.Name }}-secret-tls
{{- end }}
