apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.n8n.encryption.key | b64enc | quote }}
  {{- if .Values.n8n.basicAuth.enabled }}
  basic-auth-user: {{ .Values.n8n.basicAuth.user | b64enc | quote }}
  basic-auth-password: {{ .Values.n8n.basicAuth.password | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.n8n.database.type "postgresdb" }}
  database-password: {{ .Values.n8n.database.postgresdb.password | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.n8n.database.type "mysqldb" }}
  database-password: {{ .Values.n8n.database.mysqldb.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.n8n.smtp.enabled }}
  smtp-password: {{ .Values.n8n.smtp.password | b64enc | quote }}
  {{- end }} 