# Default values for n8n.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.n8n.io/n8nio/n8n
  # You can choose from the following versions:
  # - latest
  # - 1.85.4
  # - 1.84.3
  # - 1.83.2
  # - 1.82.3
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"


resources:
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi

n8n:
  encryption:
    key: ""  # Required: Your encryption key for n8n
  basicAuth:
    enabled: false
    user: ""
    password: ""
  database:
    type: sqlite  # Can be "sqlite", "postgresdb", or "mysqldb"
    postgresdb:
      host: ""
      port: 5432
      database: n8n
      user: n8n
      password: ""
    mysqldb:
      host: ""
      port: 3306
      database: n8n
      user: n8n
      password: ""
  smtp:
    enabled: false
    host: ""
    port: 587
    user: ""
    password: ""
    sender: ""
    ssl: false
  webhook:
    enabled: true
    timeout: 10000
  execution:
    timeout: 3600
    maxTimeout: 7200
  generic:
    timezone: UTC
  telemetry:
    enabled: false
  logs:
    level: info
